export enum CustomActionType {
    /** 关闭tips */
    CLOSE_TIP = "CLOSE_TIP",
    /** 停止接单 */
    PAUSE = "PAUSE",
    /** 工作站开始接单 */
    RESUME = "RESUME",
    /** 工作站上线 */
    ONLINE = "ONLINE",
    /** 工作站下线 */
    OFFLINE = "OFFLINE",
    /** 扫描SKU */
    SCAN_BARCODE = "SCAN_BARCODE",
    /** 切换高亮区域 */
    CHOOSE_AREA = "CHOOSE_AREA",
    /** 选择拣选任务 */
    CHOOSE_PICKING_TASK_TIP = "CHOOSE_PICKING_TASK_TIP",
    /** 扫描容器 */
    CONTAINER_ARRIVED = "CONTAINER_ARRIVED",
    /** 拆箱 */
    SPLIT_TASKS = "SPLIT_TASKS",
    /** 异常登记 */
    REPORT_ABNORMAL = "REPORT_ABNORMAL",
    /** 全部封箱 */
    ALL_SEAL_CONTAINER = "ALL_SEAL_CONTAINER",
    /** 播种墙操作,点击槽口 */
    TAP_PUT_WALL_SLOT = "TAP_PUT_WALL_SLOT",
    /** 点击扫码框事件 */
    CLICK_SCAN_CODE_BOX = "CLICK_SCAN_CODE_BOX",
    /** 挂单 */
    HANG_ORDER = "HANG_ORDER",
    /** 解绑周转箱 */
    UNBIND = "UNBIND",
    /** 播种墙绑定周转箱 */
    INPUT = "INPUT",
    /** 呼叫机器人 */
    CALL_ROBOT = "CALL_ROBOT",
    TAP_PTL = "TAP_PTL",
    CHOOSE_PUT_WALL = "CHOOSE_PUT_WALL"
}
