export enum CustomActionType {
    /** 异常登记 输送线模式 */
    INBOUND_RECEIVE_MANUAL_CONVEYOR_ABNORMAL_REGISTER_EVENT = "INBOUND_RECEIVE_MANUAL_CONVEYOR_ABNORMAL_REGISTER_EVENT",
    /** 推荐容器 异常登记 输送线模式 */
    INBOUND_RECEIVE_RECOMMEND_CONVEYOR_ABNORMAL_REGISTER_EVENT = "INBOUND_RECEIVE_RECOMMEND_CONVEYOR_ABNORMAL_REGISTER_EVENT",
    /** 异常登记 机器人模式 */
    INBOUND_ROBOT_SELECT_CONTAINER_PUTAWAY_REGISTER_EVENT = "INBOUND_ROBOT_SELECT_CONTAINER_PUTAWAY_REGISTER_EVENT",
    /** 异常登记 选择缓存货架模式 */
    INBOUND_RECEIVE_MANUAL_SHELF_ABNORMAL_REGISTER_EVENT = "INBOUND_RECEIVE_MANUAL_SHELF_ABNORMAL_REGISTER_EVENT",
    /** 异常登记 推荐缓存货架模式 */
    INBOUND_RECEIVE_RECOMMEND_SHELF_ABNORMAL_REGISTER_EVENT = "INBOUND_RECEIVE_RECOMMEND_SHELF_ABNORMAL_REGISTER_EVENT",
    /** 领用单据 */
    RECEIVE_RECEIPT = "RECEIVE_RECEIPT",
    /** 工作站上架页面扫面 LPN 或者客户单号  */
    SCAN_LPN_OR_CUSTOMER_ORDER_NO = "SCAN_LPN_OR_CUSTOMER_ORDER_NO",
    /** 上架扫描 barcode */
    INBOUND_SCAN_BARCODE = "INBOUND_SCAN_BARCODE",
    /** 上架确认事件 */
    PUT_AWAY_CONFIRM = "PUT_AWAY_CONFIRM",
    /** 上架容器离开事件 */
    PUT_AWAY_CONTAINER_LEAVE = "PUT_AWAY_CONTAINER_LEAVE",
    /** 上架选择容器格口事件 */
    CHOOSE_CONTAINER_SLOT_CODE = "CHOOSE_CONTAINER_SLOT_CODE",
    /** 已收货明细删除按钮 */
    DELETE_RECEIVE_ORDER_DETAIL = "DELETE_RECEIVE_ORDER_DETAIL",
    /** 呼叫容器 */
    CALL_CONTAINER = "CALL_CONTAINER",
    /** 切换整箱上架模式 */
    SCAN_LPN_FULL_BOX = "SCAN_LPN_FULL_BOX",
    /** 整箱上架扫料箱码 */
    WHOLE_BOX_SCAN_LPN = "WHOLE_BOX_SCAN_LPN",
    /** 整箱上架确认 */
    WHOLE_BOX_RECEIVE_CONFIRM = "WHOLE_BOX_RECEIVE_CONFIRM",
    /** 选择容器上架切换上架模式 */
    INBOUND_SWITCH_TYPE = "INBOUND_SWITCH_TYPE",
    /** 商品一品多批次弹窗 */
    SCAN_SKU_MULTIPLE_ATTRIBUTE = "SCAN_SKU_MULTIPLE_ATTRIBUTE",
    /** 商品一品多批次选择 */
    MULTIPLE_SKU_CONFIRM = "MULTIPLE_SKU_CONFIRM",
    /** 点击异常登记按钮 */
    INBOUND_ABNORMAL_TIP = "INBOUND_ABNORMAL_TIP",
    /** 异常登记确认 */
    INBOUND_ABNORMAL_CONFIRM = "INBOUND_ABNORMAL_CONFIRM",
    /** 一码多品选择SKU确认 */
    INBOUND_SCAN_BARCODE_2_MANY_SKU_CODE = "INBOUND_SCAN_BARCODE_2_MANY_SKU_CODE",
    SCAN_BARCODE_RESET = "SCAN_BARCODE_RESET",
    SKU_ORDERS_OR_OWNER_CODES_TIP = "SKU_ORDERS_OR_OWNER_CODES_TIP",
    SAME_SKU_RE_CALL_CONTAINER = "SAME_SKU_RE_CALL_CONTAINER",
    PUT_AWAY_WITHOUT_ORDER_SCAN_BARCODE = "PUT_AWAY_WITHOUT_ORDER_SCAN_BARCODE",
    PUT_AWAY_WITHOUT_ORDER_CONFIRM = "PUT_AWAY_WITHOUT_ORDER_CONFIRM",
    PUT_AWAY_WITHOUT_ORDER_CONTAINER_LEAVE = "PUT_AWAY_WITHOUT_ORDER_CONTAINER_LEAVE",
    INBOUND_WITHOUT_ORDER_SCAN_BARCODE = "INBOUND_WITHOUT_ORDER_SCAN_BARCODE"
}
