const mockData = {
    workStationId: 466985017860558850,
    warehouseCode: "MOBILESENTRIX",
    warehouseAreaId: "532948093700000000",
    stationCode: "4",
    stationName: "Robot Area-4",
    workStationStatus: "ONLINE",
    operationType: "SELECT_CONTAINER_PUT_AWAY",
    chooseArea: null,
    scanCode: "210589",
    processingType: null,
    processingInboundOrderDetailId: "579048709430579200",
    callContainerCount: 2,
    tips: null,
    workLocationArea: {
        workLocationViews: [
            {
                stationCode: "4",
                workLocationType: "ROBOT",
                workLocationCode: "JH04",
                terminalType: "PC",
                enable: true,
                workLocationSlots: [
                    {
                        workLocationCode: "JH04",
                        groupCode: "CTC_2024-05-20-000229",
                        slotCode: "",
                        level: null,
                        bay: null,
                        enable: true,
                        arrivedContainer: {
                            containerId: 538068025300095550,
                            workStationId: 466985017860558850,
                            containerCode: "A00552",
                            face: "B",
                            rotationAngle: null,
                            forwardFace: null,
                            locationCode: "",
                            workLocationCode: "JH04",
                            groupCode: "CTC_2024-05-20-000229",
                            robotCode: "1002",
                            robotType: "R",
                            level: null,
                            bay: null,
                            empty: false,
                            processStatus: "UNDO",
                            activeSlotCodes: ["BF04"],
                            disabledSlotCodes: ["BE03", "BE02", "BE01", "BD01"],
                            recommendSlotCodes: null,
                            containerAttributes: null,
                            containerSpec: {
                                id: 527491409545138200,
                                warehouseCode: "MOBILESENTRIX",
                                containerSpecCode: "BA",
                                containerSpecName: "Blue Area",
                                length: 1024,
                                width: 1224,
                                height: 2450,
                                volume: 681120000,
                                location: null,
                                description: null,
                                containerType: "SHELF",
                                containerSlotSpecs: [
                                    {
                                        containerSlotSpecCode: "BA01",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "A",
                                        bay: "01",
                                        locLevel: 1,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BA02",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "A",
                                        bay: "02",
                                        locLevel: 1,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BA03",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "A",
                                        bay: "03",
                                        locLevel: 1,
                                        locBay: 3,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BA04",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "A",
                                        bay: "04",
                                        locLevel: 1,
                                        locBay: 4,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB01",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "01",
                                        locLevel: 2,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB02",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "02",
                                        locLevel: 2,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB03",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "03",
                                        locLevel: 2,
                                        locBay: 3,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB04",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "04",
                                        locLevel: 2,
                                        locBay: 4,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB05",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "05",
                                        locLevel: 2,
                                        locBay: 5,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB06",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "06",
                                        locLevel: 2,
                                        locBay: 6,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB07",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "07",
                                        locLevel: 2,
                                        locBay: 7,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB08",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "08",
                                        locLevel: 2,
                                        locBay: 8,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB09",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "09",
                                        locLevel: 2,
                                        locBay: 9,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB10",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "10",
                                        locLevel: 2,
                                        locBay: 10,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BC01",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 50,
                                        volume: 6450000,
                                        level: "C",
                                        bay: "01",
                                        locLevel: 3,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BC02",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 50,
                                        volume: 6450000,
                                        level: "C",
                                        bay: "02",
                                        locLevel: 3,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BC03",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 50,
                                        volume: 6450000,
                                        level: "C",
                                        bay: "03",
                                        locLevel: 3,
                                        locBay: 3,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BC04",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 50,
                                        volume: 6450000,
                                        level: "C",
                                        bay: "04",
                                        locLevel: 3,
                                        locBay: 4,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BD01",
                                        face: "B",
                                        length: 430,
                                        width: 1200,
                                        height: 140,
                                        volume: 72240000,
                                        level: "D",
                                        bay: "01",
                                        locLevel: 4,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BE01",
                                        face: "B",
                                        length: 430,
                                        width: 400,
                                        height: 140,
                                        volume: 24080000,
                                        level: "E",
                                        bay: "01",
                                        locLevel: 5,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BE02",
                                        face: "B",
                                        length: 430,
                                        width: 400,
                                        height: 140,
                                        volume: 24080000,
                                        level: "E",
                                        bay: "02",
                                        locLevel: 5,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BE03",
                                        face: "B",
                                        length: 430,
                                        width: 400,
                                        height: 140,
                                        volume: 24080000,
                                        level: "E",
                                        bay: "03",
                                        locLevel: 5,
                                        locBay: 3,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BF01",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "F",
                                        bay: "01",
                                        locLevel: 6,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BF02",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "F",
                                        bay: "02",
                                        locLevel: 6,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BF03",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "F",
                                        bay: "03",
                                        locLevel: 6,
                                        locBay: 3,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BF04",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "F",
                                        bay: "04",
                                        locLevel: 6,
                                        locBay: 4,
                                        children: null
                                    }
                                ],
                                version: 1,
                                containerSlotNum: 26
                            }
                        }
                    }
                ]
            }
        ]
    },
    skuArea: {
        pickType: "CHOOSE_CONTAINER_SLOT_CODE",
        pickingViews: [
            {
                skuMainDataDTO: {
                    id: 576909719575334900,
                    skuCode: "210589",
                    warehouseCode: "MOBILESENTRIX",
                    ownerCode: "MOBILESENTRIX",
                    skuName: "Test_1",
                    style: null,
                    color: null,
                    size: null,
                    brand: null,
                    weight: null,
                    volumeDTO: null,
                    skuAttribute: {
                        imageUrl:
                            "https://static-nonprod.mobilesentrix.com/catalog/product/image/1/7/1715801371-66450d1b0b94f.webp",
                        unit: null,
                        skuFirstCategory: null,
                        skuSecondCategory: null,
                        skuThirdCategory: null,
                        skuAttributeCategory: null,
                        skuAttributeSubCategory: null
                    },
                    skuConfig: null,
                    skuPackage: null,
                    skuBarcode: null,
                    version: null
                },
                skuBatchAttributeDTO: {
                    id: null,
                    skuId: null,
                    skuAttributes: {
                        inboundDate: "20240516"
                    },
                    batchNo: null,
                    skuBatchStockIds: null
                },
                operationTaskDTOS: [
                    {
                        id: null,
                        warehouseCode: "MOBILESENTRIX",
                        taskType: "SELECT_CONTAINER_PUT_AWAY",
                        workStationId: null,
                        skuId: 576909719575334900,
                        priority: null,
                        skuBatchStockId: 1,
                        skuBatchAttributeId: 1,
                        containerStockId: 1,
                        sourceContainerCode: null,
                        sourceContainerFace: null,
                        sourceContainerSlot: null,
                        boxNo: null,
                        processStatus: "UNDO",
                        requiredQty: 10,
                        operatedQty: 0,
                        abnormalQty: 0,
                        toBeOperatedQty: 10,
                        targetLocationCode: null,
                        targetContainerCode: null,
                        transferContainerRecordId: null,
                        targetContainerSlot: null,
                        orderId: null,
                        detailId: null,
                        originalTaskId: null,
                        taskStatus: "NEW",
                        operationTaskType: null,
                        assignedStationSlot: null,
                        abnormal: false,
                        shortComplete: false,
                        updateUser: null
                    }
                ]
            }
        ],
        recommendSkuInfos: [
            {
                skuId: "576909491124178944",
                skuCode: "210591",
                skuName: "Test_2Test_2Test_2Test_2Test_2Test_2",
                ownerCode: "MOBILESENTRIX",
                sameSku: false,
                lpnCodes: ["20240515PO1"],
                barcodes: ["Test_2", "Test_22"]
            },
            {
                skuId: "576909719575334912",
                skuCode: "210589",
                skuName: "URIEOKEK_SKSKDSAURIE8889556",
                ownerCode: "MOBILESENTRIX",
                sameSku: false,
                lpnCodes: ["20240516PO4", "20240516PO2", "20240515PO1"],
                barcodes: ["Test_1", "Test_11"]
            }
        ],
        withoutOrderSkuInfos: null
    },
    putWallArea: null,
    orderArea: [
        {
            orderId: "579048709426384896",
            customerOrderNo: "753766",
            lpnCode: "20240516PO2",
            orderNo: "IN_2024-05-16-000000",
            qtyNeed: 10,
            qtyReceived: 0,
            allSkuTypes: 1,
            receivedSkuTypes: 0,
            active: true
        }
    ],
    toolbar: null,
    stationProcessingStatus: null
}

export default mockData
