const mockData = {
    workStationId: 466985017860558848,
    warehouseCode: "MOBILESENTRIX",
    warehouseAreaId: "532948029129490000",
    stationCode: "1",
    stationName: "Robot Area-1",
    workStationStatus: "ONLINE",
    operationType: "ONE_STEP_RELOCATION",
    chooseArea: null,
    scanCode: null,
    processingType: null,
    processingInboundOrderDetailId: null,
    callContainerCount: null,
    tips: null,
    workLocationArea: {
        workLocationViews: [
            {
                stationCode: "1",
                workLocationType: "ROBOT",
                workLocationCode: "JH01",
                terminalType: "PC",
                enable: true,
                workLocationSlots: [
                    {
                        workLocationCode: "JH01",
                        groupCode: "CTC_2024-09-11-000670",
                        slotCode: "",
                        level: null,
                        bay: null,
                        enable: true,
                        arrivedContainer: {
                            containerId: 612583256667331589,
                            workStationId: 466985017860558848,
                            containerCode: "A00085",
                            face: "B",
                            rotationAngle: null,
                            forwardFace: null,
                            locationCode: "src",
                            workLocationCode: "JH001",
                            pickLocationType: null,
                            groupCode: "CTC_2024-09-11-000670",
                            robotCode: "6002",
                            robotType: "R",
                            level: null,
                            bay: null,
                            empty: false,
                            processStatus: "UNDO",
                            activeSlotCodes: ["BA01"],
                            disabledSlotCodes: null,
                            recommendSlotCodes: null,
                            containerAttributes: null,
                            containerSpec: {
                                id: "527483394704150528",
                                warehouseCode: "MOBILESENTRIX",
                                containerSpecCode: "RA",
                                containerSpecName: "Red Area",
                                length: 1024,
                                width: 1224,
                                height: 2450,
                                volume: 577920000,
                                location: null,
                                description: "Overstock",
                                containerType: "SHELF",
                                containerSlotSpecs: [
                                    {
                                        containerSlotSpecCode: "BA01",
                                        face: "B",
                                        length: 430,
                                        width: 600,
                                        height: 140,
                                        volume: 36120000,
                                        level: "A",
                                        bay: "1",
                                        locLevel: 1,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BA02",
                                        face: "B",
                                        length: 430,
                                        width: 600,
                                        height: 140,
                                        volume: 36120000,
                                        level: "A",
                                        bay: "2",
                                        locLevel: 1,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB01",
                                        face: "B",
                                        length: 430,
                                        width: 1200,
                                        height: 140,
                                        volume: 72240000,
                                        level: "B",
                                        bay: "1",
                                        locLevel: 2,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BC01",
                                        face: "B",
                                        length: 430,
                                        width: 400,
                                        height: 140,
                                        volume: 24080000,
                                        level: "C",
                                        bay: "1",
                                        locLevel: 3,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BC02",
                                        face: "B",
                                        length: 430,
                                        width: 400,
                                        height: 140,
                                        volume: 24080000,
                                        level: "C",
                                        bay: "2",
                                        locLevel: 3,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BC03",
                                        face: "B",
                                        length: 430,
                                        width: 400,
                                        height: 140,
                                        volume: 24080000,
                                        level: "C",
                                        bay: "3",
                                        locLevel: 3,
                                        locBay: 3,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BD01",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "D",
                                        bay: "1",
                                        locLevel: 4,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BD02",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "D",
                                        bay: "2",
                                        locLevel: 4,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BD03",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "D",
                                        bay: "3",
                                        locLevel: 4,
                                        locBay: 3,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BD04",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "D",
                                        bay: "4",
                                        locLevel: 4,
                                        locBay: 4,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BE01",
                                        face: "B",
                                        length: 430,
                                        width: 1200,
                                        height: 140,
                                        volume: 72240000,
                                        level: "E",
                                        bay: "1",
                                        locLevel: 5,
                                        locBay: 1,
                                        children: null
                                    }
                                ],
                                version: 0,
                                containerSlotNum: 11
                            }
                        }
                    },
                    {
                        workLocationCode: "JH01",
                        groupCode: "CTC_2024-09-11-000670",
                        slotCode: "tar",
                        level: null,
                        bay: null,
                        enable: true,
                        arrivedContainer: {
                            containerId: 612583256667331611,
                            workStationId: 466985017860558848,
                            containerCode: "A00086",
                            face: "B",
                            rotationAngle: null,
                            forwardFace: null,
                            locationCode: "tar",
                            workLocationCode: "JH001",
                            pickLocationType: null,
                            groupCode: "CTC_2024-09-11-000670",
                            robotCode: "6002",
                            robotType: "R",
                            level: null,
                            bay: null,
                            empty: false,
                            processStatus: "UNDO",
                            activeSlotCodes: ["BD03"],
                            disabledSlotCodes: null,
                            recommendSlotCodes: null,
                            containerAttributes: null,
                            containerSpec: {
                                id: "527483394704150528",
                                warehouseCode: "MOBILESENTRIX",
                                containerSpecCode: "RA",
                                containerSpecName: "Red Area",
                                length: 1024,
                                width: 1224,
                                height: 2450,
                                volume: 577920000,
                                location: null,
                                description: "Overstock",
                                containerType: "SHELF",
                                containerSlotSpecs: [
                                    {
                                        containerSlotSpecCode: "BA01",
                                        face: "B",
                                        length: 430,
                                        width: 600,
                                        height: 140,
                                        volume: 36120000,
                                        level: "A",
                                        bay: "1",
                                        locLevel: 1,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BA02",
                                        face: "B",
                                        length: 430,
                                        width: 600,
                                        height: 140,
                                        volume: 36120000,
                                        level: "A",
                                        bay: "2",
                                        locLevel: 1,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB01",
                                        face: "B",
                                        length: 430,
                                        width: 1200,
                                        height: 140,
                                        volume: 72240000,
                                        level: "B",
                                        bay: "1",
                                        locLevel: 2,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BC01",
                                        face: "B",
                                        length: 430,
                                        width: 400,
                                        height: 140,
                                        volume: 24080000,
                                        level: "C",
                                        bay: "1",
                                        locLevel: 3,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BC02",
                                        face: "B",
                                        length: 430,
                                        width: 400,
                                        height: 140,
                                        volume: 24080000,
                                        level: "C",
                                        bay: "2",
                                        locLevel: 3,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BC03",
                                        face: "B",
                                        length: 430,
                                        width: 400,
                                        height: 140,
                                        volume: 24080000,
                                        level: "C",
                                        bay: "3",
                                        locLevel: 3,
                                        locBay: 3,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BD01",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "D",
                                        bay: "1",
                                        locLevel: 4,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BD02",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "D",
                                        bay: "2",
                                        locLevel: 4,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BD03",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "D",
                                        bay: "3",
                                        locLevel: 4,
                                        locBay: 3,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BD04",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "D",
                                        bay: "4",
                                        locLevel: 4,
                                        locBay: 4,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BE01",
                                        face: "B",
                                        length: 430,
                                        width: 1200,
                                        height: 140,
                                        volume: 72240000,
                                        level: "E",
                                        bay: "1",
                                        locLevel: 5,
                                        locBay: 1,
                                        children: null
                                    }
                                ],
                                version: 0,
                                containerSlotNum: 11
                            }
                        }
                    }
                ]
            }
        ]
    },
    skuArea: {
        pickType: null,
        pickingViews: null,
        recommendSkuInfos: null,
        withoutOrderSkuInfos: null
    },
    putWallArea: null,
    orderArea: null,
    toolbar: null,
    stationProcessingStatus: "WAIT_ROBOT"
}

export default mockData
