const mockData = {
    workStationId: 466985017860558850,
    warehouseCode: "MOBILESENTRIX",
    warehouseAreaId: "532948093700000000",
    stationCode: "1",
    stationName: "Robot Area-1",
    workStationStatus: "ONLINE",
    operationType: "WITHOUT_ORDER_PUT_AWAY",
    chooseArea: null,
    scanCode: null,
    processingType: null,
    processingInboundOrderDetailId: null,
    callContainerCount: 2,
    tips: null,
    workLocationArea: {
        workLocationViews: [
            {
                stationCode: "1",
                workLocationType: "ROBOT",
                workLocationCode: "JH01",
                terminalType: "PC",
                enable: true,
                workLocationSlots: [
                    {
                        workLocationCode: "JH01",
                        groupCode: "CTC_2024-05-20-000010",
                        slotCode: "",
                        level: null,
                        bay: null,
                        enable: true,
                        arrivedContainer: {
                            containerId: 538068025300095700,
                            workStationId: 466985017860558850,
                            containerCode: "A00674",
                            face: "B",
                            rotationAngle: null,
                            forwardFace: null,
                            locationCode: "",
                            workLocationCode: "JH01",
                            groupCode: "CTC_2024-05-20-000010",
                            robotCode: "1002",
                            robotType: "R",
                            level: null,
                            bay: null,
                            empty: false,
                            processStatus: "UNDO",
                            activeSlotCodes: null,
                            disabledSlotCodes: [
                                "BB10",
                                "BB08",
                                "BB09",
                                "BF04",
                                "BB06",
                                "BF03",
                                "BB07",
                                "BE03",
                                "BF02",
                                "BB04",
                                "BC04",
                                "BE02",
                                "BF01",
                                "BB05",
                                "BC03",
                                "BE01",
                                "BA03",
                                "BB02",
                                "BC02",
                                "BD01",
                                "BA04",
                                "BB03",
                                "BC01",
                                "BA01",
                                "BA02",
                                "BB01"
                            ],
                            recommendSlotCodes: null,
                            containerAttributes: null,
                            containerSpec: {
                                id: 527491409545138200,
                                warehouseCode: "MOBILESENTRIX",
                                containerSpecCode: "BA",
                                containerSpecName: "Blue Area",
                                length: 1024,
                                width: 1224,
                                height: 2450,
                                volume: 681120000,
                                location: null,
                                description: null,
                                containerType: "SHELF",
                                containerSlotSpecs: [
                                    {
                                        containerSlotSpecCode: "BA01",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "A",
                                        bay: "01",
                                        locLevel: 1,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BA02",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "A",
                                        bay: "02",
                                        locLevel: 1,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BA03",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "A",
                                        bay: "03",
                                        locLevel: 1,
                                        locBay: 3,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BA04",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "A",
                                        bay: "04",
                                        locLevel: 1,
                                        locBay: 4,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB01",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "01",
                                        locLevel: 2,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB02",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "02",
                                        locLevel: 2,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB03",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "03",
                                        locLevel: 2,
                                        locBay: 3,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB04",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "04",
                                        locLevel: 2,
                                        locBay: 4,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB05",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "05",
                                        locLevel: 2,
                                        locBay: 5,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB06",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "06",
                                        locLevel: 2,
                                        locBay: 6,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB07",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "07",
                                        locLevel: 2,
                                        locBay: 7,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB08",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "08",
                                        locLevel: 2,
                                        locBay: 8,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB09",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "09",
                                        locLevel: 2,
                                        locBay: 9,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BB10",
                                        face: "B",
                                        length: 430,
                                        width: 120,
                                        height: 50,
                                        volume: 2580000,
                                        level: "B",
                                        bay: "10",
                                        locLevel: 2,
                                        locBay: 10,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BC01",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 50,
                                        volume: 6450000,
                                        level: "C",
                                        bay: "01",
                                        locLevel: 3,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BC02",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 50,
                                        volume: 6450000,
                                        level: "C",
                                        bay: "02",
                                        locLevel: 3,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BC03",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 50,
                                        volume: 6450000,
                                        level: "C",
                                        bay: "03",
                                        locLevel: 3,
                                        locBay: 3,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BC04",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 50,
                                        volume: 6450000,
                                        level: "C",
                                        bay: "04",
                                        locLevel: 3,
                                        locBay: 4,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BD01",
                                        face: "B",
                                        length: 430,
                                        width: 1200,
                                        height: 140,
                                        volume: 72240000,
                                        level: "D",
                                        bay: "01",
                                        locLevel: 4,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BE01",
                                        face: "B",
                                        length: 430,
                                        width: 400,
                                        height: 140,
                                        volume: 24080000,
                                        level: "E",
                                        bay: "01",
                                        locLevel: 5,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BE02",
                                        face: "B",
                                        length: 430,
                                        width: 400,
                                        height: 140,
                                        volume: 24080000,
                                        level: "E",
                                        bay: "02",
                                        locLevel: 5,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BE03",
                                        face: "B",
                                        length: 430,
                                        width: 400,
                                        height: 140,
                                        volume: 24080000,
                                        level: "E",
                                        bay: "03",
                                        locLevel: 5,
                                        locBay: 3,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BF01",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "F",
                                        bay: "01",
                                        locLevel: 6,
                                        locBay: 1,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BF02",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "F",
                                        bay: "02",
                                        locLevel: 6,
                                        locBay: 2,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BF03",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "F",
                                        bay: "03",
                                        locLevel: 6,
                                        locBay: 3,
                                        children: null
                                    },
                                    {
                                        containerSlotSpecCode: "BF04",
                                        face: "B",
                                        length: 430,
                                        width: 300,
                                        height: 140,
                                        volume: 18060000,
                                        level: "F",
                                        bay: "04",
                                        locLevel: 6,
                                        locBay: 4,
                                        children: null
                                    }
                                ],
                                version: 1,
                                containerSlotNum: 26
                            }
                        }
                    }
                ]
            }
        ]
    },
    skuArea: {
        pickType: null,
        pickingViews: null,
        recommendSkuInfos: [
            {
                skuId: "541263140067872768",
                skuCode: "A811",
                skuName:
                    "A811EKRKKKfjjdifdsofposdjiofSIOJIESJFSFKDSJFGOPAOPoposdfksdkofdsokfiesdpfgdsijfjisodfjiodsijgfdsjgijsdijsjposirtretrdfgdfhfhgfhgfhgjhgjghjhjghgjghjghjhgjhgjghjhgjhgjh",
                ownerCode: "MOBILESENTRIX",
                sameSku: false,
                lpnCodes: [""],
                barcodes: ["A811"]
            }
        ],
        withoutOrderSkuInfos: [
            {
                skuId: "541263140067872768",
                skuCode: "A811",
                skuName:
                    "A811EKRKKKfjjdifdsofposdjiofSIOJIESJFSFKDSJFGOPAOPoposdfksdkofdsokfiesdpfgdsijfjisodfjiodsijgghfhfsdisiadjsafsaidhasdiashdasdsadjsadasdsajdsadashfdsjgijsffgdgfgfdgdfgdfgdfgfdgdfgfdgdfgfdgfreteertedijsjposi",
                ownerCode: "MOBILESENTRIX",
                barcodes: ["A811"]
            }
        ]
    },
    putWallArea: null,
    orderArea: null,
    toolbar: null,
    stationProcessingStatus: null
}

export default mockData
